Initial
cloudposse/terraform-template-user-data-nfs pull request #1
Opened 2017-08-02 12:43 UTC by goruha

## What
* User data nfs

## Why
* We need nfs mount for ec2 instances

2017-08-03 06:26 UTC, osterman commented on main.tf
> +resource "null_resource" "default" {
Use `tf_label`

2017-08-03 06:27 UTC, osterman commented on user_data.sh
> +
This should include the ev env file (and not assume it's already been imported)

2017-08-03 06:27 UTC, osterman requested changes
See inline comments.

2017-08-04 09:19 UTC, goruha commented on user_data.sh
> +
It imported for user data by default

2017-08-09 17:54 UTC, osterman approved these changes

2017-08-09 18:17 UTC, merged